### ISSUE TITLE
Update web player to use skin/features from LivepeerDesktop

### ISSUE THREAD

**Issue by dob** [livepeer/LivepeerDesktop#12]
Would it be easy to take the built assets in Livepeer Desktop and deploy them at our player.html web player url?

This way we'd get fullscreen support and better controls for the player?

If there is not a direct path to easily doing this then it's probably ok to avoid it for now and to instead just come up with a better strategy for the web player.

**Comment by ericxtang** [comment]
Just added the [repo](https://github.com/livepeer/livepeer-gateway) to the front-end team.  It's a pretty simple code base.  @buildog let me know if you have any questions.

**Comment by buildog** [comment]
tracked inside https://github.com/livepeer/livepeer-gateway/issues/1
